# Generated by Django 5.2.17 on 2026-08-21

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0028_survey_created_by_survey_inventory_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(help_text="Stable public publisher code used in signed wall URLs.", max_length=64, unique=True, validators=[django.core.validators.RegexValidator("^[a-z][a-z0-9-]{2,63}$")])),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("callback_url", models.URLField(blank=True, help_text="HTTPS server-to-server endpoint receiving signed outcomes.", max_length=2000)),
                ("postback_enabled", models.BooleanField(default=False)),
                ("payout_percent", models.DecimalField(decimal_places=2, default=Decimal("70.00"), help_text="Percentage of source CPI credited to this publisher.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal("0.00")), django.core.validators.MaxValueValidator(Decimal("100.00"))])),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("encrypted_signing_secret", models.TextField(blank=True, editable=False)),
                ("signing_secret_last_four", models.CharField(blank=True, editable=False, max_length=4)),
                ("signing_secret_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("api_key_hash", models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ("api_key_prefix", models.CharField(blank=True, editable=False, max_length=16)),
                ("api_key_last_four", models.CharField(blank=True, editable=False, max_length=4)),
                ("api_key_changed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("api_key_last_used_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_user", models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="offerwall_publisher", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "slug"]},
        ),
        migrations.CreateModel(
            name="OfferClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("external_user_id", models.CharField(db_index=True, max_length=160)),
                ("source_cpi_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("payout_percent_snapshot", models.DecimalField(decimal_places=2, max_digits=5)),
                ("payout_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("status", models.CharField(db_index=True, default="initiated", max_length=20)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="offerwall_click", to="surveys.surveyattempt")),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="offer_clicks", to="offerwall.publisher")),
                ("survey", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="offerwall_clicks", to="surveys.survey")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RewardLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("external_user_id", models.CharField(db_index=True, max_length=160)),
                ("entry_type", models.CharField(choices=[("credit", "Credit"), ("reversal", "Reversal")], db_index=True, max_length=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("click", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="offerwall.offerclick")),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reward_ledger", to="offerwall.publisher")),
                ("survey", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="offerwall_ledger", to="surveys.survey")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PostbackDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(max_length=32)),
                ("callback_url", models.URLField(blank=True, max_length=2000)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("delivered", "Delivered"), ("failed", "Failed"), ("skipped", "Skipped")], db_index=True, default="pending", max_length=12)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("response_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("click", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postback_deliveries", to="offerwall.offerclick")),
                ("ledger_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="postback_deliveries", to="offerwall.rewardledgerentry")),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postback_deliveries", to="offerwall.publisher")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WallVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("external_user_id", models.CharField(db_index=True, max_length=160)),
                ("entry_nonce", models.CharField(max_length=80)),
                ("country_code", models.CharField(blank=True, db_index=True, max_length=8)),
                ("device", models.CharField(blank=True, max_length=40)),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("entry_timestamp", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wall_visits", to="offerwall.publisher")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="offerclick",
            name="visit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="clicks", to="offerwall.wallvisit"),
        ),
        migrations.CreateModel(
            name="OfferOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_excluded", models.BooleanField(db_index=True, default=False)),
                ("title_override", models.CharField(blank=True, max_length=500)),
                ("payout_percent_override", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0.00")), django.core.validators.MaxValueValidator(Decimal("100.00"))])),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offer_overrides", to="offerwall.publisher")),
                ("survey", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offerwall_overrides", to="surveys.survey")),
            ],
            options={
                "ordering": ["publisher", "survey"],
                "constraints": [models.UniqueConstraint(fields=("publisher", "survey"), name="unique_publisher_offer_override")],
            },
        ),
        migrations.AddConstraint(model_name="rewardledgerentry", constraint=models.UniqueConstraint(fields=("click", "entry_type"), name="unique_click_ledger_type")),
        migrations.AddConstraint(model_name="rewardledgerentry", constraint=models.UniqueConstraint(condition=models.Q(("entry_type", "credit")), fields=("publisher", "external_user_id", "survey"), name="unique_publisher_user_offer_credit")),
        migrations.AddIndex(model_name="postbackdelivery", index=models.Index(fields=["status", "next_attempt_at"], name="postback_retry_idx")),
        migrations.AddConstraint(model_name="postbackdelivery", constraint=models.UniqueConstraint(fields=("click", "event_type"), name="unique_click_postback_event")),
        migrations.AddIndex(model_name="wallvisit", index=models.Index(fields=["publisher", "external_user_id", "-created_at"], name="wall_visit_user_idx")),
        migrations.AddConstraint(model_name="wallvisit", constraint=models.UniqueConstraint(fields=("publisher", "entry_nonce"), name="unique_publisher_wall_nonce")),
        migrations.AddIndex(model_name="offerclick", index=models.Index(fields=["publisher", "external_user_id", "survey", "-created_at"], name="offer_click_user_idx")),
        migrations.AddConstraint(model_name="offerclick", constraint=models.UniqueConstraint(fields=("visit", "survey"), name="unique_visit_offer_click")),
    ]
