# Generated by Django 5.2.17 on 2026-08-21

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerwall", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherPayoutRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("currency", models.CharField(max_length=3)),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("approved", "Approved"), ("processing", "Processing"), ("paid", "Paid"), ("rejected", "Rejected"), ("canceled", "Canceled")], db_index=True, default="pending", max_length=12)),
                ("payout_method", models.CharField(max_length=80)),
                ("publisher_note", models.CharField(blank=True, max_length=500)),
                ("admin_note", models.CharField(blank=True, max_length=500)),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("available_balance_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publisher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payout_requests", to="offerwall.publisher")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_offerwall_payouts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [models.Index(fields=["publisher", "status", "-requested_at"], name="publisher_payout_status_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="offerwall_payout_positive_amount")],
            },
        )
    ]
