# Generated by Django 5.2.17 on 2026-08-21 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0003_publisherportalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('responsive', 'Responsive web'), ('desktop', 'Desktop'), ('mobile', 'Mobile')], default='responsive', max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('website_name', models.CharField(max_length=160)),
                ('website_url', models.URLField(max_length=500)),
                ('postback_url', models.URLField(blank=True, help_text='Optional placement-specific HTTPS outcome endpoint.', max_length=2000)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_multiplier', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('100000.000000'))])),
                ('respondent_id_parameter', models.CharField(default='uid', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{0,31}$', 'Use 1–32 letters, numbers or underscores and start with a letter.')])),
                ('campaign_id_parameter', models.CharField(default='campaign_id', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{0,31}$', 'Use 1–32 letters, numbers or underscores and start with a letter.')])),
                ('affiliate_sub_parameter', models.CharField(default='subid', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{0,31}$', 'Use 1–32 letters, numbers or underscores and start with a letter.')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='offerwall.publisher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wallvisit',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='offerwall.publisherplacement'),
        ),
        migrations.AddIndex(
            model_name='publisherplacement',
            index=models.Index(fields=['publisher', 'is_active', '-created_at'], name='placement_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='publisherplacement',
            constraint=models.UniqueConstraint(fields=('publisher', 'name'), name='unique_publisher_placement_name'),
        ),
    ]
