# Generated by Django 5.2.17 on 2026-08-21 12:18

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_existing_placements(apps, schema_editor):
    from offerwall.security import encrypt_signing_secret, generate_signing_secret

    Placement = apps.get_model("offerwall", "PublisherPlacement")
    for placement in Placement.objects.all().iterator():
        raw_secret = generate_signing_secret()
        placement.status = "active" if placement.is_active else "paused"
        placement.postback_enabled = bool(placement.postback_url)
        placement.encrypted_postback_secret = encrypt_signing_secret(raw_secret)
        placement.postback_secret_last_four = raw_secret[-4:]
        placement.postback_secret_changed_at = timezone.now()
        placement.save(
            update_fields=[
                "status",
                "postback_enabled",
                "encrypted_postback_secret",
                "postback_secret_last_four",
                "postback_secret_changed_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0004_publisherplacement_wallvisit_placement_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publisherplacement',
            name='placement_active_idx',
        ),
        migrations.AddField(
            model_name='postbackdelivery',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postback_deliveries', to='offerwall.publisherplacement'),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='allowed_domains',
            field=models.TextField(blank=True, help_text='Optional additional domains, one per line. The website domain is always allowed.'),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='encrypted_postback_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='postback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='postback_secret_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='postback_secret_last_four',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='publisherplacement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=12),
        ),
        migrations.RunPython(migrate_existing_placements, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='publisherplacement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='wallvisit',
            name='affiliate_sub_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='wallvisit',
            name='external_campaign_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='publisherplacement',
            index=models.Index(fields=['publisher', 'status', '-created_at'], name='placement_active_idx'),
        ),
    ]
