# Generated by Django 5.2.17 on 2026-08-21 20:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0009_publisher_number_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_user_id', models.CharField(max_length=160)),
                ('encrypted_name', models.TextField(editable=False)),
                ('encrypted_email', models.TextField(editable=False)),
                ('email_hash', models.CharField(editable=False, max_length=64)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('verification_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verification_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_banned', models.BooleanField(db_index=True, default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_respondents', to='offerwall.publisherplacement')),
                ('last_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_respondents', to='offerwall.publisherplacement')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respondents', to='offerwall.publisher')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='wallvisit',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='offerwall.respondentprofile'),
        ),
        migrations.AddIndex(
            model_name='respondentprofile',
            index=models.Index(fields=['publisher', 'is_banned', '-last_seen_at'], name='respondent_supplier_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='respondentprofile',
            constraint=models.UniqueConstraint(fields=('publisher', 'external_user_id'), name='unique_publisher_respondent_sid'),
        ),
        migrations.AddConstraint(
            model_name='respondentprofile',
            constraint=models.UniqueConstraint(fields=('publisher', 'email_hash'), name='unique_publisher_respondent_email'),
        ),
    ]
