# Generated by Django 5.2.17 on 2026-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0010_respondentprofile_wallvisit_respondent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherportalaccount',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publisherportalaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publisherportalaccount',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publisherportalaccount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='publisherportalaccount',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
