# Generated by Django 5.2.17 on 2026-08-22 10:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_live_publishers_and_backfill_conversions(apps, schema_editor):
    Publisher = apps.get_model("offerwall", "Publisher")
    OfferConversion = apps.get_model("offerwall", "OfferConversion")
    OfferConversionEvent = apps.get_model("offerwall", "OfferConversionEvent")
    RewardLedgerEntry = apps.get_model("offerwall", "RewardLedgerEntry")
    WallVisit = apps.get_model("offerwall", "WallVisit")

    # Publishers already live before this release retain their immediate-credit
    # behavior. Publishers created after the migration use the model default.
    Publisher.objects.all().update(reward_hold_hours=0)

    credits = RewardLedgerEntry.objects.filter(entry_type="credit").select_related(
        "click", "click__attempt"
    )
    for credit in credits.iterator(chunk_size=500):
        click = credit.click
        attempt = click.attempt
        transaction_id = str(attempt.pid or attempt.rid or click.public_id)[:160]
        if OfferConversion.objects.filter(
            publisher_id=credit.publisher_id,
            source_transaction_id=transaction_id,
        ).exists():
            transaction_id = f"{transaction_id[:140]}-{click.pk}"
        reversal = RewardLedgerEntry.objects.filter(
            click_id=click.pk,
            entry_type="reversal",
        ).first()
        placement_id = (
            WallVisit.objects.filter(pk=click.visit_id)
            .values_list("placement_id", flat=True)
            .first()
        )
        status = "reversed" if reversal else "approved"
        conversion = OfferConversion.objects.create(
            click_id=click.pk,
            publisher_id=credit.publisher_id,
            placement_id=placement_id,
            survey_id=credit.survey_id,
            external_user_id=credit.external_user_id,
            source_transaction_id=transaction_id,
            source_amount=click.source_cpi_snapshot or credit.amount,
            supplier_amount=credit.amount,
            currency=credit.currency,
            status=status,
            risk_score=0,
            risk_reasons=[],
            requires_manual_review=False,
            hold_until=credit.created_at,
            approved_at=credit.created_at,
            reversed_at=reversal.created_at if reversal else None,
            decision_reason="Migrated verified reward history",
        )
        OfferConversion.objects.filter(pk=conversion.pk).update(
            created_at=credit.created_at,
            updated_at=(reversal.created_at if reversal else credit.created_at),
        )
        RewardLedgerEntry.objects.filter(pk=credit.pk).update(
            conversion_id=conversion.pk,
            status="voided" if reversal else "available",
            available_at=credit.created_at,
            released_at=credit.created_at,
        )
        if reversal:
            RewardLedgerEntry.objects.filter(pk=reversal.pk).update(
                conversion_id=conversion.pk,
                status="available",
                available_at=reversal.created_at,
                released_at=reversal.created_at,
            )
        created_event = OfferConversionEvent.objects.create(
            conversion_id=conversion.pk,
            event_type="created",
            idempotency_key=f"conversion:{conversion.public_id}:created",
            payload={"migration": True},
        )
        final_event = OfferConversionEvent.objects.create(
            conversion_id=conversion.pk,
            event_type="reversed" if reversal else "approved",
            idempotency_key=(
                f"conversion:{conversion.public_id}:{'reversed' if reversal else 'approved'}"
            ),
            payload={"migration": True},
        )
        OfferConversionEvent.objects.filter(pk=created_event.pk).update(
            created_at=credit.created_at
        )
        OfferConversionEvent.objects.filter(pk=final_event.pk).update(
            created_at=reversal.created_at if reversal else credit.created_at
        )


def reverse_live_publisher_compatibility(apps, schema_editor):
    apps.get_model("offerwall", "Publisher").objects.all().update(
        reward_hold_hours=72
    )


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0012_offerwalladminportalaccount'),
        ('surveys', '0028_survey_created_by_survey_inventory_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='reward_hold_hours',
            field=models.PositiveIntegerField(default=72, help_text='Hours a verified conversion remains pending before supplier earnings become withdrawable. Existing integrations can use zero for immediate release.', validators=[django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AddField(
            model_name='publisher',
            name='risk_review_threshold',
            field=models.PositiveSmallIntegerField(default=70, help_text='Conversions at or above this risk score require manual approval.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='rewardledgerentry',
            name='available_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardledgerentry',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardledgerentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending hold'), ('available', 'Available'), ('voided', 'Voided')], db_index=True, default='available', max_length=12),
        ),
        migrations.CreateModel(
            name='OfferConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_user_id', models.CharField(db_index=True, max_length=160)),
                ('source_transaction_id', models.CharField(db_index=True, max_length=160)),
                ('source_reference_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending hold'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=12)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('requires_manual_review', models.BooleanField(db_index=True, default=False)),
                ('hold_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversion', to='offerwall.offerclick')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_offerwall_conversions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='offerwall.publisherplacement')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='offerwall.publisher')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerwall_conversions', to='surveys.survey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rewardledgerentry',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='offerwall.offerconversion'),
        ),
        migrations.CreateModel(
            name='OfferConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, max_length=16)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='offerwall.offerconversion')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RunPython(
            preserve_live_publishers_and_backfill_conversions,
            reverse_live_publisher_compatibility,
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['status', 'requires_manual_review', 'hold_until'], name='conversion_release_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['publisher', 'status', '-created_at'], name='pub_conversion_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerconversion',
            constraint=models.UniqueConstraint(fields=('publisher', 'source_transaction_id'), name='unique_publisher_conversion_transaction'),
        ),
        migrations.AddIndex(
            model_name='offerconversionevent',
            index=models.Index(fields=['conversion', 'event_type', 'created_at'], name='conversion_event_timeline_idx'),
        ),
    ]
