# Generated by Django 5.2.17 on 2026-08-22 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0013_publisher_reward_hold_hours_and_more'),
        ('surveys', '0028_survey_created_by_survey_inventory_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisherpayoutrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Monthly billing statement', 'verbose_name_plural': 'Monthly billing statements'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='reward_hold_hours',
            field=models.PositiveIntegerField(default=72, help_text='Hours a verified conversion remains pending before supplier earnings become eligible for monthly billing. Existing integrations can use zero for immediate release.', validators=[django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.CreateModel(
            name='OfferwallInventoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['survey__local_id'],
            },
        ),
        migrations.AddField(
            model_name='publisherpayoutrequest',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherpayoutrequest',
            name='billing_period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherpayoutrequest',
            name='generated_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisherpayoutrequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='publisherpayoutrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_period_start__isnull', False)), fields=('publisher', 'currency', 'billing_period_start'), name='unique_publisher_monthly_billing'),
        ),
        migrations.AddField(
            model_name='offerwallinventoryrule',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offerwall_inventory_rule', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='offerwallinventoryrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_offerwall_inventory_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
