# Generated by Django 5.2.17 on 2026-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerwall', '0017_placement_allocation_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementeventpostback',
            name='event_type',
            field=models.CharField(choices=[('complete', 'Completed'), ('terminate', 'Terminated'), ('over_quota', 'Over quota'), ('quality_terminate', 'Quality terminated'), ('security', 'Security terminated'), ('reversal', 'Reversal')], max_length=24),
        ),
    ]
